services:
  crdb:
    image: cockroachdb/cockroach:v23.1.12
    container_name: sumup_db
    command: >
      start-single-node
      --http-addr=:8080
      --listen-addr=:26257
      --sql-addr=:5433
      --accept-sql-without-tls
      --cache=1GB
    ports:
      - "5433:5433"
      - "8088:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      COCKROACH_DATABASE: sumup
      COCKROACH_USER: sumup
      COCKROACH_PASSWORD: sumup
    networks:
      - composenet

networks:
  composenet:
    name: composenet
    driver: bridge
